### ISSUE TITLE
Add instructions in a Help/About page

### ISSUE THREAD

**Issue by mossroy** [jeena/FeedMonkey#1]
The application works great.
But, at my first use, I had not found that you can switch between articles by swiping right and left. I also did not find you can mark as unread by holding a tap on an article.
In fact, I found these features in the source code ;-)

It would be better to inform the user in any way

**Comment by jeena** [comment]
Yeah that is true, I want to add small bubbles on first use which tell you what you can do in this or this view, but I think it also would need a bottom bar with icons so you can do this stuff by clicking on them.

**Comment by mossroy** [comment]
Yes, you're probably right

**Comment by jeena** [comment]
I added a "Set unread" button and a bubble which tells about swiping.
