### ISSUE TITLE
keep wide images from breaking layout

### ISSUE THREAD

**Issue by jancborchardt** [jeena/FeedMonkey#18]
currently images wider than the viewport will cause a horizontal scrollbar. This is quite annoying, and it would probably be better to just force the maximum width of images to 100% of the parent. Something like `.article img { max-width: 100%; }`

**Comment by jeena** [comment]
Which version are you using? I have actually fixed that, see https://github.com/jeena/FeedMonkey/blob/master/css/screen.css#L146-L158

**Comment by jancborchardt** [comment]
Ok, probably this works in the latest version. What could be improved though is that currently images also have some margin to left and right much like the text. They could span the whole width though to be a bit bigger.
