### ISSUE TITLE
confusing circle

### ISSUE THREAD

**Issue by jancborchardt** [jeena/FeedMonkey#19]
This circle in the UI is quite confusing. It took me some time until I grasped that it was something like an unread count. It’s quite a strange form of feedback if you constantly have something like 200 unread feeds and only read a few at a time – then it’s only a confusing circle. :)

**Comment by jeena** [comment]
Any idea on how to improve it? I still really want to have something to indicate how far I've come in reading.

**Comment by jancborchardt** [comment]
I’d say a count is probably better, or both in combination to also have a slight visual indicator – just have the number inside of the circle. And that is also related to the »mark read/unread« toggle so grouping that makes sense.

**Comment by jeena** [comment]
Yeah that is a good idea actually, I will try to implement inside of the circle.
