### ISSUE TITLE
Add a way to modify settings after first login

### ISSUE THREAD

**Issue by mossroy** [jeena/FeedMonkey#2]
I did not find any way to modify my settings after a first successful login.
I saw in the code it was stored in LocalStorage.

It would be good to put a button somewhere to go to the settings page

**Comment by jeena** [comment]
Yeah I think I will add a settings button somewhere to change stuff like that.

**Comment by jeena** [comment]
I added a settings view and there within a "Log out" button which lets you log out and shows the login screen again.
