### ISSUE TITLE
pull to refresh

### ISSUE THREAD

**Issue by jancborchardt** [jeena/FeedMonkey#21]
Would be cool to have integrated pull to refresh in the list instead of a clunky dedicated refresh button. Hook.js seems to be the best library for that: http://usehook.com/ / https://github.com/jordansinger/hook.js/

**Comment by jeena** [comment]
I tried it once and I have to say that sadly Firefox OS devices can't do all the animations etc. as smooth as a iPhone or Android devise, they're just too slow. It is therefor I chose to use a button instead. We can try that in a year or something but for now I don't think it is appropriate.
