### ISSUE TITLE
automatically check backend

### ISSUE THREAD

**Issue by jancborchardt** [jeena/FeedMonkey#22]
Currently on initial setup there is a switcher for »Tiny Tiny RSS« and »ownCloud News« – not much changes interface-wise when these are toggled, just the placeholder for the server address.

It’s possible to detect if it’s TT-RSS or ownCloud, right? There should not be a choice, just a small text: »You can connect to ownCloud News and Tiny Tiny RSS«

**Comment by jeena** [comment]
I would appreciate a pull request fixing this, but sadly it doesn't look like I will have the time figuring out how to implement the detection, etc.
