### ISSUE TITLE
mark read/unread icon and feedback

### ISSUE THREAD

**Issue by jancborchardt** [jeena/FeedMonkey#25]
Currently the mark read/unread icon and the feedback is a bit confusing. When opening an article, an article is effectively read, but the icon/button still looks as if it’s unread.

Pressing the »x« marks the article as read and changes the button/icon to a checkmark. Pressing a checkmark to mark something as unread is very confusing.

The problem is that entypo doesn’t have two symmetric icon for read and unread. They have an »eye«, but not a strikethrough eye. Even then it would be confusing what to do. :)

Maybe it’s a good intermediate solution to use the checkmark instead of the x and the eye icon instead of the checkmark. x is very strange because it has more of a »delete« or »close« meaning.

@jeena what do you think?

**Comment by jancborchardt** [comment]
Oh and also, when opening an article, button/icon should already be switched to the eye (or currently checkmark).

Maybe in addition we should use bold an normal font weight for the titles? Bold for unread, normal for read? That’s additional feedback which is quite commonly used for unread items.

**Comment by jeena** [comment]
Yes yeah, you know I have struggled with a decision about that for several days because of the things you said like the font not having a good representation of read/unread, I also wasn't sure how do do the "read" mark thing because right now a article is marked as read _after_ you go to the next article, not while opening the article.

**Comment by jeena** [comment]
Fixed by https://github.com/jeena/FeedMonkey/commit/de93b8059afbdc17b0adc6f5ef042dda45331c49

**Comment by jancborchardt** [comment]
Great stuff, thank you!
