### ISSUE TITLE
swiping between articles when scrolled down has issues

### ISSUE THREAD

**Issue by jancborchardt** [jeena/FeedMonkey#26]
When I’m scrolled down in an article and want to swipe to the next or previous one, oftentimes it doesn’t scroll up to the beginning of the next article but rather has me end up at a similar scroll position as I was at the previous article.

As 2 articles have no relation to each other scroll-wise, the scroll position should always be reset to the very top when swiping to an unread article.

Maybe a thought for the future would be that the scroll position should be saved for already opened articles so you could continue where you left off – that’s only a vague idea though and I’m not sure if that’s always useful. Maybe something for starred items though.

**Comment by jeena** [comment]
Could it be that you experience this bug? https://github.com/jeena/FeedMonkey/issues/9

**Comment by jancborchardt** [comment]
No, that’s different. I suppose #9 is about horizontal swipe conflicting a bit with vertical scroll (which is an issue I also have).

This however is about when you are scrolled down in an article (let’s say the height of 5 viewports) and then swipe to the next one, sometimes the next one is already scrolled down (in that case, the scroll height you had for the previous article, 5 viewports). This only happens sometimes, but more often that it works correctly – which I would expect to be showing the top of the article.

**Comment by jancborchardt** [comment]
So I suppose a `scrollTo();` on a swipe event would fix that.

**Comment by jeena** [comment]
That is odd because that is exactly like it is implemented https://github.com/jeena/FeedMonkey/blob/master/js/App.js#L121 and it never happened to me.

**Comment by jeena** [comment]
I hope https://github.com/jeena/FeedMonkey/commit/28ce177e178f906fe61c424a83fb41fa3110dbb8 fixes this too.
