### ISSUE TITLE
request to get featured on the Firefox Marketplace

### ISSUE THREAD

**Issue by jancborchardt** [jeena/FeedMonkey#27]
@jeena just mail editor@mozilla.com and request for FeedMonkey to be featured. :)

**Comment by jeena** [comment]
Hehe cool :D we'll see if it will be, I assume it would need to be able to use more then just TTRSS and ownCloud News as its backend.

**Comment by jancborchardt** [comment]
Nah, just mail them! :) FeedMonkey is awesome!

**Comment by jeena** [comment]
Ok I just wrote en email, we'll see how it goes, thanks for suggesting it :)

**Comment by jancborchardt** [comment]
Nice! :)

**Comment by jeena** [comment]
Wohoo! Thanks for suggesting it, they wrote back and said it will be featured very soon (this weekend)!

**Comment by jancborchardt** [comment]
Cool! :) Let me know if it is for a specific category or globally.
Litewrite is featured in Utilities and Productivity and I'd like it to be
globally featured as well.

**Comment by jeena** [comment]
I just saw that it is featured already, and it is globally, see: https://marketplace.firefox.com/category/all/featured :D

**Comment by jancborchardt** [comment]
Hm, I can’t really see it featured yet. Tried also without being logged in and with private browsing.

**Comment by jeena** [comment]
That is odd, did you go to the featured page (not the front page) and all the way down, the last featured application?
