### ISSUE TITLE
enable on Firefox Marketplace for Android

### ISSUE THREAD

**Issue by jancborchardt** [jeena/FeedMonkey#28]
When browsing marketplace.firefox.com from an Android tablet or smartphone the app is not findable.

Check yourself by searching https://marketplace.firefox.com/search?q=owncloud from an Android device.

You should enable it in the app settings to be available on all platforms. :)

**Comment by jeena** [comment]
As far as I know it got removed because it is not possible to run a privileged app like FeedMonkey is on Android.
