### ISSUE TITLE
Cors problem with owncloud

### ISSUE THREAD

**Issue by Mte90** [jeena/FeedMonkey#29]
I see that after the login an alert with error : 0.
After some debugging the problem is the cors -.-'

it's possible fix the bug?

**Comment by jeena** [comment]
Yeah I could uses {mozSystem: true} like I do for TTRSS, but normally ownCloud News sends the CORS headers. Which version are you using? Could you make me a account so I could test it?

**Comment by Mte90** [comment]
I have no idea of the version of the news app because i use an hosting for owncloud.
The version of ownlocud is 5.0.13, but the android app for the owncloud news work without problem.

**Comment by jeena** [comment]
Ah I see hm, are you able to make a account for me for testing purposes?

**Comment by Mte90** [comment]
i have a plan on owncube.com that isn't able to create account.

**Comment by jeena** [comment]
Ok, I see, are you a developer and able to test if replacing new XMLHttpRequest(); with new XMLHttpRequest({mozSystem: true}); in the file https://github.com/jeena/FeedMonkey/blob/master/js/OwnCloud.js line 49 and 237 and test it.

If not, then I will make a special version for you and explain how you can install it on your mobile phone.

**Comment by Mte90** [comment]
Works!
Only one problem if there isn't new news the page are blank.
A message i think that is better.

**Comment by jeena** [comment]
Ah ok, cool, then I will change that for the next version, thanks for reporting it!

**Comment by Mte90** [comment]
There is a chance for the Firefox Desktop version?

**Comment by jeena** [comment]
Hm I don't know, the UI is not really build for desktop or tablet. It is more probable that I will implement ownCloud support into https://github.com/jeena/feedthemonkey some day.

**Comment by Mte90** [comment]
For me the ui isn't a problem but i think that the mozSystem that is only for FirefoxOS is the problem.

**Comment by jeena** [comment]
Fixed by https://github.com/jeena/FeedMonkey/commit/35f4825596f0a3ac9cda23971232204f37a87d1c
