### ISSUE TITLE
Login/password should be optional

### ISSUE THREAD

**Issue by mossroy** [jeena/FeedMonkey#3]
tt-rss can be configured with 'SINGLE_USER_MODE'=true in config.php
In this case, no login/password is required.

**Comment by jeena** [comment]
Ah, didn't know that, but how do you authenticate that it is you then?

**Comment by mossroy** [comment]
In this case, tt-rss does not authenticate you at all.
But, if necessary, you can add an external way to "secure" your server.
In my case, I use basic HTTP authentication, over SSL, but there might be other ways to do it.
By the way, the basic HTTP authentication is well supported : it asked me for the user/password at login time

**Comment by jeena** [comment]
Ah I didn't know that the basic auth was working that way. I will remove the check for username and password then.
