### ISSUE TITLE
Article list does not get refreshed any more after a few hours or one day, with tt-rss backend : NOT_LOGGED_IN response not handled

### ISSUE THREAD

**Issue by mossroy** [jeena/FeedMonkey#30]
Hi,

I'm using FeedMonkey with a tt-rss server (over https).
This tt-rss server is configured with no user/password. It's secured with a Basic HTTP Authentication (user/password) configured on the frontal Apache server.

It works pretty well after installation. Synchronization works correctly in both ways (articles read on tt-rss or on FeedMonkey)

But, after ~ one day, FeedMonkey does not refresh any more : the new articles that appeared on tt-rss do not appear on FeedMonkey, even if I tap the refresh icon. There is some network activity when refreshing, though.

I have this behavior both with version 0.3 from Marketplace, and with latest version from github.

If I logout in FeedMonkey and login again, everything comes back to normal. Same thing if I reinstall the application.
So I suspect that it comes from something that the application stores locally (the tt-rss server config, or the articles themselves?)

**Comment by jeena** [comment]
Sadly I will not have the time to look at this for at least one month. So if you have the posibility to look at it I would appreciate that.

On April 7, 2014 10:05:33 AM CEST, mossroy notifications@github.com wrote:

> Hi,
> 
> I'm using FeedMonkey with a tt-rss server (over https).
> This tt-rss server is configured with no user/password. It's secured
> with a Basic HTTP Authentication (user/password) configured on the
> frontal Apache server.
> 
> It works pretty well after installation. Synchronization works
> correctly in both ways (articles read on tt-rss or on FeedMonkey)
> 
> But, after ~ one day, FeedMonkey does not refresh any more : the new
> articles that appeared on tt-rss do not appear on FeedMonkey, even if I
> tap the refresh icon. There is some network activity when refreshing,
> though.
> 
> I have this behavior both with version 0.3 from Marketplace, and with
> latest version from github.
> 
> If I logout in FeedMonkey and login again, everything comes back to
> normal. Same thing if I reinstall the application.
> So I suspect that it comes from something that the application stores
> locally (the tt-rss server config, or the articles themselves?)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jeena/FeedMonkey/issues/30

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Alvarord** [comment]
Hello, 

I have a similar problem specially when I have a lot of unread articles, in the simulator I have been able to seen that there is a problem in this line at App.js

localStorage.unread_articles = JSON.stringify(this.unread_articles);

An exception is launched, and you can see a: NS_ERROR_DOM_QUOTA_REACHED

I'm trying to gather how to solve it or avoid it. With tt-rss I have tried to limit the amount of news without success.

I will need to test it more, but maybe this clue can help somebody to follow the issue faster than me.

**Comment by Alvarord** [comment]
Hello, 

I think have solved the issue with the following patch.

The stringify was throwing an exception that was not capture, the idea behind the patch is just to try to stringify anytime and if it fails just populate the interface with the last that has been seen and keep a copy in LocalStorage for future reuses.

```
--- a/js/App.js
+++ b/js/App.js
@@ -153,13 +153,16 @@ App.prototype.gotUnreadFeeds = function(new_articles) {
        } else {

                this.unread_articles = this.unread_articles.concat(new_articles);
-
-               if(new_articles.length > 0) {
+               try {
+                       localStorage.new_articles = JSON.stringify(this.unread_articles);
+                       localStorage.old_articles=localStorage.new_articles;
+                       localStorage.new_articles=null;
                        this.backend.getUnreadFeeds(this.gotUnreadFeeds.bind(this), this.unread_articles);
-               } else {
-                       localStorage.unread_articles = JSON.stringify(this.unread_articles);
-                       this.populateList();
-               }               
+               } catch (e) {
+                       alert("Issue with the amount of data to process")
+               }
+               this.populateList();
+
        }
 };

```

**Comment by mossroy** [comment]
Thanks Alvarord for your tests and research.

I've applied your patch on App.js (in a local copy), and tested it on my device.
But it seems that FeedMonkey now goes into an infinite loop : the network icon is always blinking, until I stop FeedMonkey.

**Comment by Alvarord** [comment]
Interesting, that should happens if your backend always gives you feeds, so the exception that arises in my case it is not happening in your. 

Could you launch your version in the simulator and put a break point just before the new_articles.length? In the simulator you can check the http request and response that you are receiveing, check the new_articles.length that is receiving the application from your backend.

I have a biggest patch, but I think I have introduced another issue that I'm debugging. Once I'm confident with it I will push it to my branch.

**Comment by Alvarord** [comment]
Can you try the branch that I created. 

https://github.com/Alvarord/FeedMonkey/branches/master20140429-issue30

I know it is not very clean but I think it can help you to track where is your issue.

**Comment by mossroy** [comment]
OK thanks : it's installed on my device and configured with my tt-rss server.
I'll tell you how it works

**Comment by mossroy** [comment]
I have the same behavior with this version. Here is what I tried : 
- Did a fresh install of FeedMonkey from your branch, on my device (Geeksphone Peak v1.1.0hd)
- Configured it on my tt-rss server
- It worked well : I see the unread articles, they get updated to and from the server etc. I see the debug messages you added ("Downloaded : x articles, Reached y bytes")
- I left the device for the night
- In the next morning, there are new unread articles on my server (around 30)
- I run FeedMonkey again. On startup, it seems to access my server (there is some network activity) but nothing happens : the list inside FeedMonkey is not updated. I have no error message and not any of your debug messages
- Since then, whatever I do (refresh in FeedMonkey and/or change unread states on the server), FeedMonkey is stuck with the old article list. The only workaround I found is to logout in FeedMonkey (or uninstall/reinstall it), and configure the tt-rss server again
  It's the same behavior I had before.

Anyway, don't bother too much for me on that issue. It might be due to the fact that I use an outdated version of FxOS (v1.1). I will be able to upgrade it in a few weeks and will try again.
I tried in the Simulator, but could not connect to my tt-rss server. It's probably due to the fact that I use SSL encryption with a self-signed certificate (that I manually installed on my device)

**Comment by Alvarord** [comment]
Ok, I will try to replicate that issue in my Peak.

I remembered that I had an issue with Firefox browser inside the Peak with self-signed certificate and then I decided to get a domain and a proper SSL certificate. But maybe I can run the test locally again.

I will keep you posted if I replicate it.

Advice me if an update solved it.

**Comment by Alvarord** [comment]
Hello, 

I think that the issue is in your configuration of the tt-rss. Check this value por default

define('SESSION_COOKIE_LIFETIME', 86400); //Exactly 24 hours.

In your config.php on the tt-rss.The cookie is not used in one day and then the backend return:

{"seq":null,"status":1,"content":{"error":"NOT_LOGGED_IN"}}

And the program is not processing that. 

@mossroy  Could you try to modify the value to longest time to validate that the issue is there?

Kind regards.

**Comment by mossroy** [comment]
Ahah, I think it's very likely that you found where the problem comes from!
I've set (temporarily) the cookie lifetime to 0 (no expiration), and reinstalled FeedMonkey from jeena github master.
I should be able to confirm (or not) tomorrow or the day after.

Thanks a lot for your investigation!

**Comment by mossroy** [comment]
Well, unfortunately, this does not seem to be better. I've also tried with the version available from the Marketplace : I have the same behavior.
I also noticed that it takes less than 24 hours to have the symptoms : I would say 8 or 12 hours are enough.

Anyway, as I said before, don't bother too much for now. I'll test again with FxOS 1.3 as soon as I will be able to upgrade my device. It should give me more tools to investigate (like the remote debugging)

**Comment by mossroy** [comment]
I could upgrade my device to FxOS 1.3.

I faced a separate issue, regarding basic HTTP authentication : #34

As a workaround, I disabled the basic HTTP authentication, and have the same behavior : after a few hours (less than 8 apparently), the article list does not get refreshed any more.
I'll try to investigate in the Simulator

**Comment by jeena** [comment]
It could be because the basic auth. The authentication is saved by the OS for some time but after some time it is invalidated or something and should be refreshed. Because FeedMonkey doesn't know anything about it and never gets any new data anymore.

Could you try to use the normal authentication just to test if this fixes the issue?

**Comment by mossroy** [comment]
It's not related to basic auth.
I've disabled it on my server and tested again. I used your latest git version, rebooted the device to make sure there was no pending authentication, and connected to my server.
So there is no authentication : no basic auth, and no tt-rss authentication either.
Same symptom : it works for a few hours, and then the list does not get refreshed. There's no error message.

If it works everywhere else, I guess it's probably related to the way my server is configured. I'll try to investigate in the Simulator when I find some time.

**Comment by mossroy** [comment]
After some debugging in the Simulator :
The "getHeadlines" call leads to the following response from tt-rss :
{"seq":null,"status":1,"content":{"error":"NOT_LOGGED_IN"}}
exactly as stated by @Alvarord 
And this is not handled by FeedMonkey for now.

But this error seems to come from the fact that I had put tt-rss in "single user mode" (define('SINGLE_USER_MODE', true); in config.php). In this mode, the authentication of tt-rss is disabled, and everything is done as admin user. But, for some reason, it gives this behavior with FeedMonkey.
If I disable the single user mode (default value), it works.
The COOKIE_LIFETIME of tt-rss does not seem to matter here.

So I have at least a workaround for now : disable basic auth AND disable single user mode
NB : I'll change the title of this issue to be more specific

**Comment by jeena** [comment]
Ah, that then I'd say is a bug in FeedMonkey. The question is, how to fix it? The right thing to do when we get NOT_LOGGED_IN would be to show you the login view. But this wouldn't help with the SINGLE_USER_MODE. I will have to test it out, thanks for finding this out so far.

**Comment by mossroy** [comment]
On the other hand, is it logical for tt-rss to send a NOT_LOGGED_IN when it is configured in single user mode, where the user never logs in?

**Comment by mossroy** [comment]
Even with basic auth disabled and single user mode disabled, I manage to have the NOT_LOGGED_IN response, and the same symptoms (list not refreshed).
But it took more than a few hours. I think this time it's because of the SESSION_COOKIE_LIFETIME of 24 hours. Like suggested by @Alvarord 
I've set it to 0 to check that.
So it looks like that, in any case, this response needs to be handled by FeedMonkey

**Comment by mossroy** [comment]
Well, setting the SESSION_COOKIE_LIFETIME to 0 did not seem to help : I still got the NOT_LOGGED_IN after ~ one day without launching FeedMonkey

**Comment by mossroy** [comment]
I've investigated a bit more this issue.
Here is what I understood from the way authentication is maintained with tt-rss backend : 
- After a successful login, a cookie is sent on the client side. Its life time is set by the parameter SESSION_COOKIE_LIFETIME. But this cookie is not used by FeedMonkey
- Instead, FeedMonkey stores the session_id generated by tt-rss (inside its localStorage area), and uses it for every future communication with the backend. FeedMonkey does not handle any lifetime for this session_id
- On the tt-rss backend, this session_id is stored in a database table called ttrss_sessions. It is stored with an expiration date/time, with value max(SESSION_COOKIE_LIFETIME, 86400) (see https://github.com/gothfox/Tiny-Tiny-RSS/blob/master/include/sessions.php ). It means that, for tt-rss, this session will expire after 24 hours of inactivity (or less is the SESSION_COOKIE_LIFETIME is less). If a client tries to use an expired session, it sends a NOT_LOGGED_IN error
- In FeedMonkey, this NOT_LOGGED_IN error is handled as any other error from the backend : it displays the saved unread articles

To try to solve this issue, I modified the FeedMonkey code to handle the NOT_LOGGED_IN error : it's easy but the main issue is that the login and password are not saved in the localStorage of FeedMonkey. So it's necessary to ask them again to the user. After that, tt-rss generates a new session_id and it works again.

But I find it not ideal to be forced to type the login/password every 24 hours of inactivity...
There would be at least 2 possibilities to improve that : 
- be able to extend the session lifetime on the server side. The 24 hour limit is currently hardcoded in tt-rss, so we would have to convince to move that to a parameter. A drawback is that it would extend all the session lifetimes, not only the ones from FeedMonkey
- storing the username/password in the localStorage of FeedMonkey is another way to do it. I find it's a better way. But IMHO it should be an option that the user can select or not, because it can be a security issue to store the password

What's your opinion?

**Comment by Alvarord** [comment]
I changed in my tt-rss the lifetime of the cookie.

In the config.php file in my installation:
        //define('SESSION_COOKIE_LIFETIME', 86400);
        define('SESSION_COOKIE_LIFETIME',604800); //Modify to improve experience in the mobile

I don-t like your second option i prefer that when feedmoneky receive a NOT_LOGGED_IN, jump to login and to store server name (especially if it is long is quite a pain in the ass to write it again) and user and ONLY needed to fill the password.

I was thinking about doing this and I tried once without success ;-)

**Comment by mossroy** [comment]
If I understood correctly the code I read, increasing the SESSION_COOKIE_LIFETIME will not change the fact that you will have to re-signin every 24 hours of inactivity.
The only way to do that on the server side is to modify sessions.php : line 12 modify the way the variable $session_expire is set.
But that can only be seen as a temporary workaround, because this will be overwritten with next tt-rss upgrade.

Regarding keeping the username in FeedMonkey, I added this feature and commited it on my Github repo.

**Comment by Alvarord** [comment]
It does a max:

$session_expire = max(SESSION_COOKIE_LIFETIME, 86400);

For me it seems to work properly.

So if you increase the value it will take the bigger one. I tried something like your commit but i found some problem, I hope in any case you make it work. ;-)

**Comment by mossroy** [comment]
Mmmmh... you're right : it's a max not a min ;-)
So yes, increasing the SESSION_COOKIE_LIFETIME should work without modifying the php :+1: 
I've set the same value as you (one week) and will test that.

What got me confused in my first tests was that I had set this variable to 0, based on the comment in config.php : "0 means cookie will be deleted when browser closes". It's true, but in this case the session on the server will still expire after 24 hours, because of this line of code.

**Comment by Alvarord** [comment]
In any case keep going with your patch!!! It will be quite useful.

**Comment by jeena** [comment]
@mossroy will you make it a pull request when you're done testing?

**Comment by mossroy** [comment]
Sure, that was the idea.

**Comment by mossroy** [comment]
After a bit testing, it seems to be working fine for me.
I've created the pull request #35

**Comment by mossroy** [comment]
For me, the Pull Request solves this issue.
Feel free to reopen it if you disagree
