### ISSUE TITLE
Issue with Jester. It reads 2 articles with swipe and with the arrow it reads only one.

### ISSUE THREAD

**Issue by Alvarord** [jeena/FeedMonkey#32]
Hello,

I'm checking where is the issue but it seems that Jester with the version I have in the mobile 2.0 and in the simulator 1.3 send 2 messages anytime I do a swipe.

I will try to validate simulator versions and with the mobile. But I noticed it in the mobile and then I see that the issue happens in the simulator too.

**Comment by Alvarord** [comment]
I'm afraid that the issue is random. Sometimes happens to me and sometimes not. I was able to replicate it twice in my Peak and in the simulator but at this time it is not happening with the Peak.

The problem is that with the swipe it advance 2 articles and mark both as readed, but on the interface you only see one.

**Comment by jeena** [comment]
Jetster seems not to be in development anymore. I assume we should replace it with something else like they suggest, for example: https://github.com/jairajs89/Touchy.js
