### ISSUE TITLE
Basic HTTP authentication 

### ISSUE THREAD

**Issue by mossroy** [jeena/FeedMonkey#34]
This is a minor issue, as it does not happen on a standard/simple installation of tt-rss.

On my installation of tt-rss, I disabled the authentication of tt-rss, and replaced it by a basic HTTP authentication, handled by the HTTP server (Apache, in my case).
As my server hosts a lot of services, it's a way to have a single and common way to authenticate for several services.

Unfortunately, it's not currently supported by FeedMonkey. To be more precise, it was supported with FxOS 1.1, but not with FxOS >=1.3 (I did not test with 1.2). I suppose something has changed in the way XHR is handled.
Symptom : after setting the HTTP address in FeedMonkey, it fails with "error: 401 Authorization Required", and does not display any article.

Looking at the code, it looks like the 401 response code is not handled by FeedMonkey (which is normal because it expects a standard tt-rss authentication).
Maybe the code could be enhanced to use the provided login/password in case of a 401 error code.

I'll try to investigate if I find some time.

**Comment by jeena** [comment]
I'd be very happy to get a pull request.

**Comment by jeena** [comment]
But sadly I don't think I will have the time to invest to find out on how to implement it, therefor I am closing this issue for now. But as I said, when you're able to fix it I'll be happy to get a pull request.
