### ISSUE TITLE
FeedMonkey not posting updates back to server

### ISSUE THREAD

**Issue by djibux** [jeena/FeedMonkey#36]
I have been using FeedMonkey for a few days.  I am pretty happy with the application, but it doesn't seem to post back updates to the server.  What I mean is that, when I read an article, it is not marked as read on the server.  Same thing with the starred articles: they are only being starred locally.  As soon as I refresh from the app, all local modifications (read articles, starred articles) are being reset.

I'm using ownCloud 7.0.1 with FeedMonkey 0.4.1.
I tried over https and http and I have the same issue in both cases.

**Comment by jeena** [comment]
I was able to reproduce it with ownCloud 7, the app sends a PUT with the data and gets a OK 200 from the server. Still the server doesn't save the read or starred state. I will need to dive deeper into the server code to understand why that happens, just haven't had the time yet.

**Comment by djibux** [comment]
Cool !

 Thanks for your time.
 --
 djib

**Comment by jeena** [comment]
@djibux Do you think you could try it now with the change? Do you know how to get it from here on your device?

**Comment by djibux** [comment]
I'm quite new to Firefox OS so I'm not quite sure what's the best way to do that... but I'm willing to learn.

Apparently I could use the "push to device" feature in Firefox OS Simulator.  Do you know of any better solution?  Could you point to the documentation?

**Comment by djibux** [comment]
You rock man, it works now (reading state, starred articles, etc.).

I used the App Manager, it's really convenient !

**Comment by jeena** [comment]
Wohoo! Thanks for the bug report and testing, I will package a new version and send it to the Marketplace.
