### ISSUE TITLE
Add a publish button to article view

### ISSUE THREAD

**Issue by Bonbadil** [jeena/FeedMonkey#38]
Hello,

TinyTinyRss allow user to mark an article as "published", and published articles are available as a RSS feed. I use this as tweetos use retweet, for exemple.
Can a publish button be added next to the star one when an article is viewed?

**Comment by jeena** [comment]
I would love a pull request for this, I don't know when I will have the time to implement it myself.

**Comment by Bonbadil** [comment]
Done in PR #39.
