### ISSUE TITLE
Improve error reporting when there is an XHR failure

### ISSUE THREAD

**Issue by mossroy** [jeena/FeedMonkey#4]
It's only a matter of giving more details and explanations to the user.
I tried to connect to a tt-rss server over https, for which the SSL certificate is self-signed.
XHR rejected that, which is normal.
But the application gave me an "error : 0" message, which is not very meaningful.
I suppose it comes from line 129 of TinyTinyRSS.js

**Comment by jeena** [comment]
Ah hm yeah I only show the error message TTRSS sends back but yeah, you're right it can hapen so much before it even comes to a server response.

**Comment by mossroy** [comment]
I had the same kind of message when trying to update the feeds with a not-so-good 3G connection, that probably lead to a timeout.

**Comment by jeena** [comment]
Yeah I assume that is the case, I need to read more about this things, on the desktop I never had to deal with stuff like this ;)

**Comment by jeena** [comment]
I removed the alert when status is 0 because it doesn't help anyone. I'm still not quite sure how to distinguish between any errors when the status is just 0.

**Comment by jeena** [comment]
Fixed by https://github.com/jeena/FeedMonkey/commit/89142c54c0fdadeb027a35326fd5b27dc2c46d8c
