### ISSUE TITLE
"undefined" subtitle under the article titles in the list

### ISSUE THREAD

**Issue by mossroy** [jeena/FeedMonkey#5]
In the list of articles, all my articles have 3 lines : 
- the first one displays the feed it comes from
- the second one displays the title of the article
- the third one always displays "undefined"

I suppose the third line is supposed to display something else...

**Comment by jeena** [comment]
Yea it is supposed to show a teaser, the first couple of words but I only do $(".foo").html(article.something) and if your feed doesn't have content but just a headline it will show undefined, I check for it.

**Comment by jeena** [comment]
I am checking now for the excerpt, if it is not there I don't display anything.
