### ISSUE TITLE
Application stuck with only one "undefined" line

### ISSUE THREAD

**Issue by mossroy** [jeena/FeedMonkey#6]
After a few hours using the application, it looks like I reached a state where it is "stucked".
When I start it and/or reload, there's only one line displayed, with title "undefined". If I tap it, it displays "Invalid date" :
![2013-08-25-12-34-52](https://f.cloud.github.com/assets/890923/1022333/ff74b9f2-0d7e-11e3-966b-4e63cf02d91a.png)
![2013-08-25-13-41-42](https://f.cloud.github.com/assets/890923/1022334/ff7accb6-0d7e-11e3-8535-b9799e1c4131.png)

No matter which feeds are unread on my tt-rss server, and no matter how much there are (0, 1 or more).

If I install the same application (same version) on another device, and configure it for the same server, it works correctly.

So I suppose it is a kind of corruption of the LocalStorage on my device.
I ran into a few "error :0" alerts (see previous issues I opened), so it might be the cause.
I suppose deleting the application and reinstalling it should solve the issue.

**Comment by mossroy** [comment]
I removed the application, and reinstalled it, with a more recent version.
As I expected, it worked again after this reinstallation.
This would tend to confirm it is some kind of "corruption" of the data stored locally by the application. In the sense that this data is in a state that the application can not handle properly.

In any case, it happened again after a few hours using it :
![2013-08-27-21-27-49](https://f.cloud.github.com/assets/890923/1037416/0bf8bf80-0f4f-11e3-9b81-2bd8a295a226.png)
![2013-08-27-21-27-58](https://f.cloud.github.com/assets/890923/1037417/0c2fe262-0f4f-11e3-9cb3-56faabf4e37d.png)

On my device, the 3G connection is unreliable. I suspect this "corruption" might come from some inproper error handling, but I can not say for sure

**Comment by jeena** [comment]
Hm yeah, there is not much error handling mostly just checking navigator.isOnline before doing a request. This needs to change.

**Comment by mossroy** [comment]
Great! I installed the latest version from git and will test that...

**Comment by mossroy** [comment]
Now the behavior is a bit different. But I can not say the issue is fixed.
Instead of displaying the "undefined", it always displays the same articles.
Whatever I do (reload, restart the app, re-read all of them etc), they do not disappear and are not replaced by the ones on my tt-rss server.

**Comment by jeena** [comment]
Hmmmm would you be able to alert the data you're getting from your server while this is happening? This happens if one of the articles titles is undefined: https://github.com/jeena/FeedMonkey/blob/17c100ecb318b555a74bc9ae07569646d810a368/js/App.js#L154 I'm not sure why that would be. Perhaps I should just filter out this one article instead of stoping the execution.

Do you think you could upload your OPML somewhere? It seems very strange that you would get such data from a tt-rss server :-/

**Comment by mossroy** [comment]
I added a few "alert" instructions around the XHR calls, and managed to reproduce the issue :
If my 3G access is "blocked", and I launch FeedMonkey, it first tries to call the server with operation "getHeadlines", with feed_id:-4
And XHR gets a response with satus 0, and no text (when readyState=4 of course)

After that,when I reconnect my 3G or Wifi, whenever I try to update the feeds, the XHR response is OK, with seq:null,status:1,content:error:NOT_LOGGED_IN
And the feeds are not updated.

That made me try to logout in FeedMonkey : if I login again, everything works again.
So logout/login in FeedMonkey is a workaround.

Hope this helps

**Comment by jeena** [comment]
It helps to understand it but I have sadly no idea how to fix it. The only way I can think of is to save the username and password in the app and just log you in in the background again if that should happen. But first I need to investigate on how to securly save a password on the devise.

**Comment by mossroy** [comment]
I close this issue : my 3G is now fully stable. Anyway, there is still an issue, that I described in #30
